name: document
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  web_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup
      - uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0
      - run: pnpm -r build
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: doc/dist
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        if: github.ref == 'refs/heads/main'
  web_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup
      - run: pnpm -r build
      - run: pnpm build --site http://localhost:4321/monza-editor
        working-directory: doc
      - run: pnpm preview &
        working-directory: doc
      - run: >
          go tool muffet
          --buffer-size 8192
          --exclude https://www.npmjs.com/package/.*
          http://localhost:4321/picolight/
  document:
    needs:
      - web_build
      - web_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
