name: document
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  web_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: actions/configure-pages@v5
      - run: pnpm -r build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: doc/dist
      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'
  web_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm -r build
      - run: pnpm build --site http://localhost:4321/monza-editor
        working-directory: doc
      - run: pnpm preview &
        working-directory: doc
      - run: >
          go tool muffet
          --buffer-size 8192
          http://localhost:4321/monza-editor/
  document:
    needs:
      - web_build
      - web_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
