name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  npm:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'release' || '' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: pnpm -r build
      - run: pnpm -r publish ${{ github.ref != 'refs/heads/main' && '--dry-run --no-git-checks' || '' }}
  release:
    needs:
      - npm
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
